version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/var/www/static #bind shared volume for static files
      - media_volume:/var/www/media
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d #add nginx config
      - static_volume:/var/www/static #bind shared volume for static files
      - media_volume:/var/www/media
    depends_on:
      - djangoapp

  database1:  # change db address in settings to database1!!
    image: postgres:10
    env_file:
      - ./docker-config/db/database1_env
    volumes:
      - database1_volume:/var/lib/postgresql/data

volumes:
  static_volume: #declare shared volume for static files
  database1_volume: #makes db changes persistent even after stopping container
  media_volume:
