# Generated by Django 3.0.6 on 2020-05-13 10:43

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HelpPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('map_point', djgeojson.fields.PointField(default="{'type': 'Point', 'coordinates': [0, 0]}")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Category')),
            ],
        ),
    ]
