# Generated by Django 3.0.6 on 2020-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppoint',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
