# Generated by Django 3.0.6 on 2020-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200513_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppoint',
            name='lat',
            field=models.FloatField(default=12.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helppoint',
            name='long',
            field=models.FloatField(default=23.1),
            preserve_default=False,
        ),
    ]
