# Generated by Django 3.0.6 on 2020-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200518_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppoint',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
