# Generated by Django 3.0.6 on 2020-05-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200516_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helppoint',
            old_name='title',
            new_name='popup',
        ),
    ]
