# Generated by Django 3.0.6 on 2020-05-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200517_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helppoint',
            old_name='popup',
            new_name='title',
        ),
    ]
