# Generated by Django 3.0.6 on 2020-05-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200517_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppoint',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='helppoint',
            name='long',
        ),
    ]
