# Generated by Django 3.0.6 on 2020-05-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default='<Describe yourself>', max_length=150)),
                ('picture', models.ImageField(default='standard-profile.jpg', null=True, upload_to='')),
            ],
        ),
    ]
