# Generated by Django 3.0.6 on 2020-05-19 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20200519_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_messages_from',
            field=models.ManyToManyField(related_name='unread_messages_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UnreadMessagesFrom',
        ),
    ]
