PROJECT_TITLE = "Help Map"
LOGO_PATH = "/static/logo.png"
HOST = "127.0.0.1"
CATEGORIES = ["Category1", "Category2", "Category3", ]
INITIAL_ADMIN_PASSWORD = "password"
OPENCAGE_API_KEY = 'XXXXXXXXX'
USE_DOCKER = True
USE_SQLITE = False
PRODUCTION = False
