PROJECT_TITLE = "Berlin hilft"
LOGO_PATH = "/static/logo.png"
CUSTOM_CSS = "/static/css/custom.css"
HOST = "127.0.0.1"
CATEGORIES = ["Verschenken", "Einkaufshilfe", "Homeschooling", "Helfende Hände", "Studentenjobs", "Mitfahrzentrale", ]
INITIAL_ADMIN_PASSWORD = "password"
OPENCAGE_API_KEY = 'XXXXXX'
MAPBOX_API_KEY= 'XXXXX'
AWS_API_KEY = 'XXXX'
USE_DOCKER = True
USE_SQLITE = False
PRODUCTION = False
