# Generated by Django 3.0.6 on 2020-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='belongs_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
